language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
branches:
  only:
  - master
  - develop
install: true # skip mvn install, because we essentially run the same command in the script routine
script:
  - mvn install -B -Pintegration-tests
